name = "ai-campaign-strategist"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
publish = "dist"

[[pages_build_output_dir]]
directory = "dist"

[env.production]
# Environment variables will be set in Cloudflare Pages dashboard
